apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # Base64 Encode: pgadmin@gmail.com = cGdhZG1pbkBnbWFpbC5jb20=
  PG_USER_EMAIL: cGdhZG1pbkBnbWFpbC5jb20=

  # Base64 Encode: pgadmin1234 = cGdhZG1pbjEyMzQ=
  PG_PASSWORD: cGdhZG1pbjEyMzQ=