apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # Base64 Encode: postgres = cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=

  # Base64 Encode: 12345678 = MTIzNDU2Nzg=
  DB_PASSWORD: MTIzNDU2Nzg=